// flow-typed signature: c9d492446bb8e4ae5a2d4a15f805d228
// flow-typed version: <<STUB>>/ignite-vector-icons_v^1.1.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ignite-vector-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ignite-vector-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ignite-vector-icons/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ignite-vector-icons/plugin.js' {
  declare module.exports: $Exports<'ignite-vector-icons/plugin'>;
}
