// flow-typed signature: 4acfc4b883a9fe6d34834420970b4a4b
// flow-typed version: <<STUB>>/react-native-google-signin_v^1.0.0-rc6/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-google-signin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-google-signin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-google-signin/src/GoogleSignin' {
  declare module.exports: any;
}

declare module 'react-native-google-signin/src/GoogleSigninButton.android' {
  declare module.exports: any;
}

declare module 'react-native-google-signin/src/GoogleSigninButton.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-google-signin/index' {
  declare module.exports: $Exports<'react-native-google-signin'>;
}
declare module 'react-native-google-signin/index.js' {
  declare module.exports: $Exports<'react-native-google-signin'>;
}
declare module 'react-native-google-signin/src/GoogleSignin.js' {
  declare module.exports: $Exports<'react-native-google-signin/src/GoogleSignin'>;
}
declare module 'react-native-google-signin/src/GoogleSigninButton.android.js' {
  declare module.exports: $Exports<'react-native-google-signin/src/GoogleSigninButton.android'>;
}
declare module 'react-native-google-signin/src/GoogleSigninButton.ios.js' {
  declare module.exports: $Exports<'react-native-google-signin/src/GoogleSigninButton.ios'>;
}
