@baseUrl = https://localhost/api
@contentType = application/json
@email = test@test.com
@username = testuser
@password = password

# @name signup
POST {{baseUrl}}/user/signup
content-type: {{contentType}}

{
  "email": "{{email}}",
  "username": "{{username}}",
  "password": "{{password}}"
}

###

# @name login
POST {{baseUrl}}/auth/login
content-type: {{contentType}}

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

@token = {{login.response.body.$.data.token}}

# @name protectedEndpoint
GET {{baseUrl}}/user/auth-test
Authorization: Bearer {{token}}